### PR TITLE
Fix downloads not being saved in shared storage on android 10 and above

### LINKED ISSUE #77: Downloaded files will be saved under Android/data directory on Android13
When downloading images and videos, they are saved in
`/storage/emulated/Android/data/com.ensoft.imgurviewer/files/Download`
instead of
`/storage/emulated/Download`.

[App version]
2.3.7 (download from Google Play)

[Environment]
Android13 (ZenUI and MyOS, this occurs in both)

On MyOS, this phenomenon occurred from the first installation.
On ZenUI, I was able to save it to `/storage/emulated/Download` until I initialized the app, probably because the settings had been migrated through data transfer.

### PR DESCRIPTION
**Pull request by starry-shivam**
Closes #77

### CODE REVIEW

**Comment by SpartanJ** [comment]
Awesome, thank you! Can you please reformat the file to use tabs instead of spaces so I can read the diff with more ease and also respect the project code style?

**Comment by starry-shivam** [comment]
> Awesome, thank you! Can you please reformat the file to use tabs instead of spaces so I can read the diff with more ease and also respect the project code style?

Sure, sorry it was auto formatted by my IDE, I'll push a fix in sometime

**Comment by starry-shivam** [comment]
I tried to retain the original formatting; however, it seems it still isn't showing enough spaces. I don't have much experience with tabs, and I guess my IDE is not configured to support it well, but I hope it's a bit better than before

**Review by SpartanJ — APPROVED** [review]

**Comment by SpartanJ** [comment]
Thanks again!

**Comment by ihatemakinganaccount** [comment]
@SpartanJ will you push a new release with this fix? (I also see there's #77... Idk what your plan is about that...)

**Comment by SpartanJ** [comment]
Sure, I'll do it next weekend.

**Comment by ihatemakinganaccount** [comment]
Neat

**Pull request merged**
